tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
certController:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
webhook:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
