dex:
  enabled: false

server:
  config:
    url: https://argocd.shared-services.361.money
    oidc.config: |
      name: EntraID
      issuer: https://login.microsoftonline.com/2e3bbb40-f3cf-4644-9a0e-cb0f6c977c21/v2.0
      clientID: $argocd-oidc:clientId
      clientSecret: $argocd-oidc:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
      requestedIDTokenClaims:
        groups:
          essential: true
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: alb
    hosts:
      - argocd.shared-services.361.money

configs:
  cm:
    admin.enabled: "false"
  rbac:
    policy.csv: |
      g, 361-by-finca:argocd-admins, role:admin