global:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule

redis:
  secretInit:
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
